---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
  namespace: myns
data:
  host: 
    127.0.0.1 locahost
    127.0.1.1 batcomputer

    #the folliwng lines are desireable for IPv6 capable host



  readme.txt: |
    this is a readme file