apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgg-database-deploy
  labels:
    name: bgg-database-deploy
  namespace: bggns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bgg-database-po
  template:
    metadata:
      name: bgg-database-po
      labels:
        name: bgg-database-po
    spec:
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: db-pvc
      containers:
      - name: bgg-database-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          protocol: TCP
        volumeMounts:
        - name: data-vol
          mountPath: /var/lib/mysql

---

apiVersion: v1
kind: Service
metadata:
  name: bgg-database-svc
  labels:
    name: bgg-database-svc
  namespace: bggns
spec:
  type: ClusterIP
  selector:
    name: bgg-database-po
  ports:
  - port: 3306
    targetPort: 3306


