apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-bear-deploy
  labels:
    name: dov-bear-deploy
  namespace: myns
spec:
  replicas: 3
  selector:
    matchLabels:
      name: dov-bear-po
  template:
    metadata:
      name: dov-bear-po
      labels:
        name: dov-bear-po
    spec:
      containers:
      - name: dov-bear-container
        image: chukmunnlee/dov-bear-golang:0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: INSTANCE_NAME
          value: dov-bear
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PORT
          value: "3000"
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe: 
          httpGet:
            path: /healthz
            port: 3000
        resources:
          requests:
            memory: 32Mi
            cpu: 100m
          limits:
            memory: 32Mi
            cpu: 100m

---

apiVersion: v1
kind: Service
metadata:
  name: dov-bear-hsvc
  labels:
    name: dov-bear-hsvc
  namespace: myns
spec:
  clusterIP: None
  selector:
    name: dov-bear-po
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dov-bear-hpa
  labels:
    name: dov-bear-hpa
  namespace: myns
spec:
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dov-bear-deploy
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: 
  name: deny-all
  namespace: myns
spec:
  policyTypes:
  - Ingress
  - Egress 
  podSelector:
    matchLabels:
      deny-all: "true"