apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    name: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  labels:
    name: minio-hsvc
    app: minio
  namespace: minio
spec:
  clusterIP: None
  selector: 
    name: minio-po
    app: minio
  ports:
  - name: minio-data 
    port: 9000
    targetPort: 9000
  - name: minio-console 
    port: 9090
    targetPort: 9090
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-sts
  labels:
    name: minio-sts
    app: minio
  namespace: minio
spec:
  serviceName: minio-hsvc
  replicas: 4
  selector:
    matchLabels:
      name: minio-po
      app: minio
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: minio-pvc
      labels:
        name: minio-pvc
        app: minio
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: do-block-storage-xfs
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      labels:
        name: minio-po
        app: minio
    spec:
      initContainers:
      - name: minio-init-container
        image: busybox
        command:
        - /bin/sh
        - -c
        - "chown 1001 /data"
        volumeMounts:
        - name: minio-pvc
          mountPath: /data
      containers:
      - name: minio-container
        image: bitnami/minio:2022.12.12
        imagePullPolicy: IfNotPresent
        env:
        - name: MINIO_ROOT_USER
          value: bWluaW9taW5pbw==
        - name: MINIO_ROOT_PASSWORD
          value: bWluaW9taW5pbw==
        command:
        - minio
        - server
        - --address=:9000
        - --console-address=:9090
        - http://minio-sts-{0...3}.minio-hsvc.minio.svc.cluster.local/data
        ports:
        - containerPort: 9000
        - containerPort: 9090
        volumeMounts:
        - name: minio-pvc
          mountPath: /data
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /minio/health/ready
            port: 9000
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /minio/health/live
            port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  labels:
    name: minio-svc
    app: minio
  namespace: minio
spec:
  type: ClusterIP
  selector:
    name: minio-po
    app: minio
  ports:
  - name: data
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090
---
apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: minio-ing
  labels:
    name: minio-ing
    app: minio
  namespace: minio
spec:
  ingressClassName: nginx
  rules:
  - host: data-167.172.7.170.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: minio-svc
            port: 
              name: data
  - host: console-167.172.7.170.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: minio-svc
            port: 
              name: console