apiVersion: v1 
kind: ConfigMap
metadata:
  name: bgg-backend-config 
  labels:
    name: bgg-backend-config 
  namespace: bggns
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bgg-database-svc.bggns.svc.cluster.local

---

apiVersion: v1 
kind: Secret 
metadata:
  name: bgg-backend-secret
  labels:
    name: bgg-backend-secret
  namespace: bggns 
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=

---